metricCodes <- c("Shannon_Flow", "PCT_CF", "PCT_DR", "PCT_GL", "PCT_POOL", "PCT_RA", 
                 "PCT_RI", "PCT_RN", "PCT_FAST", "PCT_SLOW", "PCT_CF_WT", "PCT_GL_WT", 
                 "PCT_POOL_WT", "PCT_RA_WT", "PCT_RI_WT", "PCT_RN_WT", "PCT_FAST_WT", 
                 "PCT_SLOW_WT", "XWDEPTH", "XWDM", "XWDA", "XWDR", "XWIDTH", "Shannon_Habitat", 
                 "XFC_AQM", "XFC_HUM", "XFC_RCK", "XFC_ALG", "XFC_LWD", "XFC_LTR", 
                 "XFC_OHV", "XFC_BRS", "XFC_UCB", "XFC_BIG", "XFC_NAT_EMAP", "XFC_NAT_SWAMP", 
                 "CFC_AQM", "CFC_HUM", "CFC_RCK", "CFC_ALG", "CFC_LWD", "CFC_LTR", 
                 "CFC_OHV", "CFC_BRS", "CFC_UCB", "W1H_BRDG", "W1H_BLDG", "W1H_LDFL", 
                 "W1H_LOG", "W1H_MINE", "W1H_ORVY", "W1H_PARK", "W1H_PSTR", "W1H_PVMT", 
                 "W1H_PIPE", "W1H_ROAD", "W1H_CROP", "W1H_VEGM", "W1H_WALL", "W1_HALL_SWAMP", 
                 "W1_HALL_EMAP", "XGB", "XGH", "XGW", "XG", "XPGVEG", "XPMGVEG", 
                 "XM", "XC", "XCM", "XPMID", "XPCAN", "XPCM", "XPCMG", "XCMG", 
                 "XCDENMID", "XCDENBK", "Shannon_Substrate", "PCT_RS", "PCT_RR", 
                 "PCT_RC", "PCT_XB", "PCT_SB", "PCT_CB", "PCT_GC", "PCT_GF", "PCT_SA", 
                 "PCT_FN", "PCT_HP", "PCT_WD", "PCT_OT", "PCT_BDRK", "PCT_BIGR", 
                 "PCT_SFGF", "PCT_SAFN", "XSDGM", "XSPDGM", "SB_PT_D50", "SB_PT_D10", 
                 "SB_PT_D25", "SB_PT_D75", "SB_PT_D90", "SB_PP_D50", "SB_PP_D10", 
                 "SB_PP_D25", "SB_PP_D75", "SB_PP_D90", "PCT_CPOM", "XEMBED", 
                 "Alkalinity as CaCO3", "pH", "Salinity", "SpecificConductivity", 
                 "Temperature", "Turbidity", "PBM_S", "PBM_V", "PBM_E", "XBKF_H", 
                 "XBKF_W", "XWV", "MXWV", "PWVZ", "Dominant Land Use", "Evidence of Fire")